[[redirects]]
  from = "https://portfolio.isaacmorrier.com/*"
  to = "https://isaacmorrier.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "web/__sapper__/export"
  trailingSlash = true
  exclude = [
    'web/__sapper__/export/service-worker-'
    'web/__sapper__/export/404'
  ]