[[redirects]]
  from = "https://isaacmorrier.com/test"
  to = "https://isaacmorrier.com/info"
  force = true
  status = 301

[[redirects]]
  from = "https://portfolio.isaacmorrier.com/*"
  to = "https://isaacmorrier.com/:splat"
  force = true
  status = 301

